### ISSUE TITLE
[ ! ] Restoring packages        Be patient... NOT WORKING

### ISSUE THREAD

**Issue by DarkPhilosophy** [laraib07/TermuxBackupTools#10]
[ ! ] Restoring packages
       Be patient...

E: Option vim: Configuration item specification must have an =<val>.

**Comment by laraib07** [comment]
Working on my side. Could't figure out what's wrong with the error message. 
try updating packages first.

**Comment by DarkPhilosophy** [comment]
Found out there was some lines like "-o" or other bizarre things...  The problem was related when it saved those installed PKG

**Comment by laraib07** [comment]
@DarkPhilosophy "-o" in script or the text file where packages are stored?

**Comment by DarkPhilosophy** [comment]
Inside the text files pkgs.bak located in Termux Backup

**Comment by laraib07** [comment]
@DarkPhilosophy Last question, Had you previously made changes to the file?

**Comment by DarkPhilosophy** [comment]
Never touch or edit anything of rewind script or backups, only use rewind -b and rewind -r

**Comment by laraib07** [comment]
Thanks, don't know what happened. It shouldn't happen. 
Use `rewind -b pkgs` and check file `pkgs.bak` located in `Termux/backup/ ` folder.
Send screenshot or copy/paste here as you see fit.
