### ISSUE TITLE
How to backup important packages in termux

### ISSUE THREAD

**Issue by Noob225566** [laraib07/TermuxBackupTools#12]
Bro i have a question can i only make backup of important packages like 
All python packages
Pip
Git
Xfce4
X11-repo 
Etc
Because i downloaded useless packages accidentally in termux thats why i wanna to create backup file of only important packages plz respond me as soon as possible plzz

**Comment by laraib07** [comment]
@Noob225566 
Just saw your issue. The script backups whole data folder. If your packages exist inside data folder then every package will be backed up.

**Comment by Noob225566** [comment]
Means if i use your tool to make my a backup of my useful packages and important packages only it makes backup of all packages inside termux including useless packages 😭😭

**Comment by laraib07** [comment]
@Noob225566 that's correct

**Comment by Noob225566** [comment]
Is there not any way to fulfil my requirement

**Comment by laraib07** [comment]
@Noob225566 If I understand correctly, you only want to backup packages. I think you can do it. 
**For the python packages part:** There was a fork of this repository which made some changes in the script to backup the list of python packages. You can also add that in you script. Something like `pip freeze > pypkglist` in the backup function of the script and `pip install -r pypkglist` in the restore function of the script.

**For the termux packages:** It is stored in `pkgs.bak` file which is a simple text file. After backing up, manually edit this file and remove the packages which you don't need.
