### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by sheeepdev** [laraib07/TermuxBackupTools#3]
I get permission denied errors when backing up home in my TermuxArch directory, is there a way to ignore these warnings because it fails to backup because of some files in the arch directory.

**Comment by laraib07** [comment]
Check termux's app permission in system settings>apps and notification
Grant storage permission if not already granted.

Or use command
`termux-setup-storage` 

I will help me understand the issue better if you could paste the error.

**Comment by sheeepdev** [comment]
its ok dont need to backup anymore
