### ISSUE TITLE
.suroot folder permission denied

### ISSUE THREAD

**Issue by Mark-Joy** [laraib07/TermuxBackupTools#4]
Thank you for the module.

There is one issue, backup failed due to permission denied in .suroot folder.
![Screenshot_2021-06-14-13-54-54-547_com termux](https://user-images.githubusercontent.com/22109528/121851646-935a2600-cd18-11eb-8cf0-c6d15876aa21.jpg)

And where can I find the backup files?

**Comment by laraib07** [comment]
I am guessing ./suroot/.bash_history have no read permission. Grant it read permission and try again.

**Comment by Mark-Joy** [comment]
Done. Thank you. Where is the backup stored?

**Comment by laraib07** [comment]
the backup is stored in `/storage/emulated/0/Termux/backup`
