### ISSUE TITLE
Can this script backup and restore to a new device?

### ISSUE THREAD

**Issue by ioogithub** [laraib07/TermuxBackupTools#5]
Is this script able to backup from one Termux installation and restore to another device? Will it set the correct user and filesystem permissions for all packages and and scripts?

I looked briefly at the code but I couldn't see if it would take care of these issues. Perhaps you could update the readme to clarify this as backing and restoring across devices may be one of the main use cases.

**Comment by laraib07** [comment]
> Is this script able to backup from one Termux installation and restore to another device? Will it set the correct user and filesystem permissions for all packages and and scripts?

Yes it will. the home directory will retain its permissions  and the packages will be reinstalled. 
Regarding user for package, termux has only on user. So no need to worry here.
 
> I looked briefly at the code but I couldn't see if it would take care of these issues. Perhaps you could update the readme to clarify this as backing and restoring across devices may be one of the main use cases.

I change my ROM quite often, haven't faced any issue yet.
