### ISSUE TITLE
[apt list --manual-installed] vs pkgs.bak

### ISSUE THREAD

**Issue by Mark-Joy** [laraib07/TermuxBackupTools#6]
Hello,
To see manual-installed package in Termux: `apt list --manual-installed`
But this list is different from your list in pkgs.bak

This will cause missing packages during restoring process, won't it?

**Comment by laraib07** [comment]
`apt list --manual-installed` also include pacakges which comes preinstalled with termux.
pkgs.bak only include packages which you installed yourself and exclude preinstalled packages. This way if termux discard any preinstalled package, it wont be installed by the script.

And to answer your question,
No it won't cause any missing packages.
