### ISSUE TITLE
Backup Pkgs: List shows pkgs that were removed/no longer installed

### ISSUE THREAD

**Issue by lmservas** [laraib07/TermuxBackupTools#7]
I just did a backup of both my home and Pkgs and happened to notice after backing up Pkgs that the list shown due to using the print option includes all packages I've installed and since deleted. Is this something I can fix? Does rewind pull an overall list from somewhere? Even Pkgs I had removed with "apt-get purge" were still there.

**Comment by laraib07** [comment]
Rewind take pkg backup from $PREFIX/var/log/apt/history.log

It only includes pkgs currently installed.

**Comment by lmservas** [comment]
I'm sorry I should have clarified and not sounded like an idiot lol. I did not mean to imply that the backup actually included Pkgs that weren't installed at the time of backup but rather just that I noticed the output list still included them and just wanted to call on your expertise and ask where it came from as that list could be valuable when rebuilding etc. And you answered my question despite my ramblings - thank you!!

**Comment by laraib07** [comment]
The script make `Installed` list of packages from `apt install packageName` and then it removes those packages which are also present in `apt remove packageName`. there may be a chance that the packages removes using `apt purge packageNames` may not be removed from `installed`.
I will look into it.
Thanks for letting me know about this.

**Comment by laraib07** [comment]
fixed in b07c4e5
